config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :user, controllers: {  
    # confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    # unlocks: 'users/unlocks',
  }, path_names: {sign_in: "login", sign_out: "logout"}

  # TODOS - to scale and refine
  resources :profile
  resources :email
  resources :timesheet
  resources :reporting
  resources :help, only: [:index]
  
  root to: 'main#index'

  # Catch-all to allow proper HTTP responses for 404, 403 and 505 errors
  get "*route_not_found.:format", :to => "application#route_not_found"
  get "*route_not_found",         :to => "application#route_not_found"
end

app/models/timesheet.rb
class Timesheet < ApplicationRecord
    belongs_to :employee
    scope :currently_logged_employee, ->(employee_id){ where(employee_id: employee_id) }
    # For reporting page
    scope :weekly_timesheets, -> { where(entry_date: Time.now.beginning_of_week(start_day = :sunday)..Time.now.end_of_week(start_day = :sunday) )}
end

app/controllers/timesheet_controller.rb
class TimesheetController < ApplicationController
  load_and_authorize_resource

  def index
    @timesheets = Timesheet.currently_logged_employee(session[:employee_id])
    @title = 'Timesheets'
  end

  def new
    @timesheet = Timesheet.new
    @timesheet_url_path = timesheet_index_path

    @title = 'Timesheets'
  end

  def edit
    @timesheet = Timesheet.find(params[:id])
    @timesheet_url_path = timesheet_path

    @title = 'Timesheets'
  end

  def show
    @timesheet = Timesheet.find(params[:id])

    @title = 'Timesheets'
  end

  def create
    # fetch employee id from stored session id

    @timesheet = Timesheet.new(timesheet_params)
    @timesheet.save

    redirect_to timesheet_index_path
  end

  def update
    @timesheet = Timesheet.find(params[:id])
    # save current employee_id
    @employee_id = @timesheet.employee_id
    
    if @timesheet.update(timesheet_params)
        redirect_to timesheet_index_path
    else
        render 'edit'
    end

  end

  def destroy
    @timesheet = Timesheet.find(params[:id])
    @timesheet.destroy

    redirect_to timesheet_index_path
  end

  private
  def timesheet_params
      params.require(:timesheet).permit(:title, :description, :entry_date, :total_hours, :status).merge(employee_id: session[:employee_id])
  end


end

app/views/timesheet/_shared-form.html.haml
-# TODOs - refining UI fields and data types
= form_with model: @timesheet, url: @timesheet_url_path, local: true, class: "form-horizontal form-label-left" do |form|
  .form-group
    = form.label(:title, "Title", class: "control-label col-md-3 col-sm-3 col-xs-12")
    .col-md-6.col-sm-6.col-xs-12
      = form.text_field(:title, id: "title", class: "form-control col-md-7 col-xs-12")
  .form-group
    = form.label(:descripton, "Description", class: "control-label col-md-3 col-sm-3 col-xs-12")
    .col-md-6.col-sm-6.col-xs-12
      = form.text_field(:description, id: "description", class: "form-control col-md-7 col-xs-12")
  .form-group
    = form.label(:entry_date, "Entry Date", class: "control-label col-md-3 col-sm-3 col-xs-12")
    .col-md-6.col-sm-6.col-xs-12{style: "display: flex; justify-content: space-between;"}
      = form.date_select :entry_date, {order: [:day, :month, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: Date.today.year - 100}, {id: "date_of_birth", required: true, class: "form-control", style: "width: 30%;"}
  .form-group
    = form.label(:total_hours, "Total Hours", class: "control-label col-md-3 col-sm-3 col-xs-12")
    .col-md-6.col-sm-6.col-xs-12
      = form.text_field(:total_hours, id: "total_hours", class: "form-control col-md-7 col-xs-12")
  .form-group
    = form.label(:status, "Status", class: "control-label col-md-3 col-sm-3 col-xs-12")
    .col-md-6.col-sm-6.col-xs-12
      = form.text_field(:status, id: "status", class: "form-control col-md-7 col-xs-12")
  .ln_solid
  .form-group
    .col-md-6.col-sm-6.col-xs-12.col-md-offset-3
      = link_to("Cancel", timesheet_index_path, class: "btn btn-primary")
      = form.submit("Save", class: "btn btn-success")

app/views/timesheet/edit.html.haml
%div
  = render "shared/body-panel/search-component"
  .clearfix
  .row
    .col-md-12.col-sm-12.col-xs-12
      .x_panel
        .x_title
          %h2
            Edit timesheet
          .clearfix
        .x_content
          %br/
          = render 'shared-form'

app/views/timesheet/index.html.haml
- cache do
  %div
    = render "shared/body-panel/search-component"
    .clearfix
      .row
        .col-md-12
          .x_panel
            .x_title
              %h2 Timesheets
              %ul.nav.navbar-right.panel_toolbox
                %li
                  %a.collapse-link
                    %i.fa.fa-chevron-up
                %li.dropdown
                  %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                    %i.fa.fa-wrench
                  %ul.dropdown-menu{:role => "menu"}
                    %li
                      %a{:href => "#"} Settings 1
                    %li
                      %a{:href => "#"} Settings 2
                %li
                  %a.close-link
                    %i.fa.fa-close
              .clearfix
            .x_content
              -# TODO - define better module name
              - if !userHasEmployeeProfile
                %h4 You have not completed your employee profile yet to log any timesheets. Please navigate to your profile tab.
              - else
                - if @timesheets.length == 0
                  -# check if no timesheets available
                  %h4 You don't have any submitted timesheets
                  %br/  
                - else
                  / start project list
                  %table.table.table-striped.projects
                    %thead
                      %tr
                        %th #
                        %th Title
                        %th Description
                        %th Entry Date
                        %th Total Hours
                        %th Status
                        %th #Edit
                    %tbody
                    - @timesheets.each do |timesheet|
                      %tr
                        %td #
                        %td= timesheet.title
                        %td= timesheet.description
                        %td= timesheet.entry_date
                        %td= timesheet.total_hours
                        %td= timesheet.status
                        %td
                          = link_to(timesheet_path(timesheet), :class => "btn btn-primary btn-xs") do 
                            %i.fa.fa-folder
                            View
                          = link_to(edit_timesheet_path(timesheet), :class=> "btn btn-info btn-xs") do 
                            %i.fa.fa-pencil
                            Edit
                          = link_to(timesheet_path(timesheet), :class=> "btn btn-danger btn-xs", method: :delete, data: {confirm: 'Are you sure you want to delete this timesheet?'}) do 
                            %i.fa.fa-trash-o
                            Delete      
                  / end project list
                  /TODO - pagination
                  -# .dataTables_wrapper
                  -#   .row
                  -#     .col-sm-5
                  -#       #datatable_info.dataTables_info{"aria-live" => "polite", :role => "status"} Showing 1 to 10 of 57 entries
                  -#     .col-sm-7
                  -#       #datatable_paginate.dataTables_paginate.paging_simple_numbers
                  -#         %ul.pagination
                  -#           %li#datatable_previous.paginate_button.previous.disabled
                  -#             %a{"aria-controls" => "datatable", "data-dt-idx" => "0", :href => "#", :tabindex => "0"} Previous
                  -#           %li.paginate_button.active
                  -#             %a{"aria-controls" => "datatable", "data-dt-idx" => "1", :href => "#", :tabindex => "0"} 1
                  -#           %li.paginate_button
                  -#             %a{"aria-controls" => "datatable", "data-dt-idx" => "2", :href => "#", :tabindex => "0"} 2
                  -#           %li.paginate_button
                  -#             %a{"aria-controls" => "datatable", "data-dt-idx" => "3", :href => "#", :tabindex => "0"} 3
                  -#           %li.paginate_button
                  -#             %a{"aria-controls" => "datatable", "data-dt-idx" => "4", :href => "#", :tabindex => "0"} 4
                  -#           %li.paginate_button
                  -#             %a{"aria-controls" => "datatable", "data-dt-idx" => "5", :href => "#", :tabindex => "0"} 5
                  -#           %li.paginate_button
                  -#             %a{"aria-controls" => "datatable", "data-dt-idx" => "6", :href => "#", :tabindex => "0"} 6
                  -#           %li#datatable_next.paginate_button.next
                  -#             %a{"aria-controls" => "datatable", "data-dt-idx" => "7", :href => "#", :tabindex => "0"} Next
                  /end - pagination
                / button
                = link_to(new_timesheet_path, :class => "btn btn-success") do
                  Log new timesheet
                / end button
      

app/views/timesheet/new.html.haml
%div
  = render "shared/body-panel/search-component"
  .clearfix
  .row
    .col-md-12.col-sm-12.col-xs-12
      .x_panel
        .x_title
          %h2
            Log a new timesheet
          .clearfix
        .x_content
          %br/
          = render 'shared-form'

app/views/timesheet/show.html.haml
- cache do
  %div
    = render "shared/body-panel/search-component"
    .clearfix
    .row
      .col-md-12.col-sm-12.col-xs-12
        .x_panel
          .x_title
            %h2
              View timesheet
            .clearfix
          .x_content
            %br/
            = form_with model: @timesheet, url: @timesheet_url_path, local: true, class: "form-horizontal form-label-left" do |form|
              .form-group
                = form.label(:title, "Title", class: "control-label col-md-3 col-sm-3 col-xs-12")
                .col-md-6.col-sm-6.col-xs-12
                  = form.text_field(:title, id: "title", class: "form-control col-md-7 col-xs-12", disabled: "disabled")
              .form-group
                = form.label(:descripton, "Description", class: "control-label col-md-3 col-sm-3 col-xs-12")
                .col-md-6.col-sm-6.col-xs-12
                  = form.text_field(:description, id: "description", class: "form-control col-md-7 col-xs-12", disabled: "disabled")
              .form-group
                = form.label(:entry_date, "Entry Date", class: "control-label col-md-3 col-sm-3 col-xs-12")
                .col-md-6.col-sm-6.col-xs-12{style: "display: flex; justify-content: space-between;"}
                  = form.date_select(:entry_date, {order: [:day, :month, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year, end_year: Date.today.year - 100}, {id: "date_of_birth", required: true, disabled: true, class: "form-control", style: "width: 30%;"})
              .form-group
                = form.label(:total_hours, "Total Hours", class: "control-label col-md-3 col-sm-3 col-xs-12")
                .col-md-6.col-sm-6.col-xs-12
                  = form.text_field(:total_hours, id: "total_hours", class: "form-control col-md-7 col-xs-12", disabled: "disabled")
              .form-group
                = form.label(:status, "Status", class: "control-label col-md-3 col-sm-3 col-xs-12")
                .col-md-6.col-sm-6.col-xs-12
                  = form.text_field(:status, id: "status", class: "form-control col-md-7 col-xs-12", disabled: "disabled")
              .ln_solid
              .form-group
                .col-md-6.col-sm-6.col-xs-12.col-md-offset-3
                  = link_to("Return to table", timesheet_index_path, class: "btn btn-primary")