config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :user, controllers: {  
    # confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    # unlocks: 'users/unlocks',
  }, path_names: {sign_in: "login", sign_out: "logout"}

  # TODOS - to scale and refine
  resources :profile
  resources :email
  resources :timesheet
  resources :reporting
  resources :help, only: [:index]
  
  root to: 'main#index'

  # Catch-all to allow proper HTTP responses for 404, 403 and 505 errors
  get "*route_not_found.:format", :to => "application#route_not_found"
  get "*route_not_found",         :to => "application#route_not_found"
end

app/views/shared/top-navigation/_main.html.haml
.top_nav
  .nav_menu
    %nav
      .nav.toggle
        %a#menu_toggle
          %i.fa.fa-bars
      %ul.nav.navbar-nav.navbar-right
        %li
          %a.user-profile.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "javascript:;"}
            %img{:alt => "", :src => "images/img.jpg"}>/
            #{current_user.username}
            %span.fa.fa-angle-down
          %ul.dropdown-menu.dropdown-usermenu.pull-right
            %li
              = link_to(profile_index_path) do
                Profile
            %li
              %a{:href => "javascript:;"}
                %span.badge.bg-red.pull-right 50%
                %span Settings
            %li
              = link_to(help_index_path) do
                Help
            %li
              = link_to(destroy_user_session_path, method: :delete) do
                %i.fa.fa-sign-out.pull-right
                Log Out