config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :user, controllers: {  
    # confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    # unlocks: 'users/unlocks',
  }, path_names: {sign_in: "login", sign_out: "logout"}

  # TODOS - to scale and refine
  resources :profile
  resources :email
  resources :timesheet
  resources :reporting
  resources :help, only: [:index]
  
  root to: 'main#index'

  # Catch-all to allow proper HTTP responses for 404, 403 and 505 errors
  get "*route_not_found.:format", :to => "application#route_not_found"
  get "*route_not_found",         :to => "application#route_not_found"
end

app/views/shared/sidebar/_footer.html.haml
.sidebar-footer.hidden-small
  %a{"data-original-title" => "Settings", "data-placement" => "top", "data-toggle" => "tooltip", :title => ""}
    %span.glyphicon.glyphicon-cog{"aria-hidden" => "true"}
  %a{"id" => "fullscreen", "data-original-title" => "FullScreen", "data-placement" => "top", "data-toggle" => "tooltip", :title => ""}
    %span.glyphicon.glyphicon-fullscreen{"aria-hidden" => "true"}
  %a{"data-original-title" => "Lock", "data-placement" => "top", "data-toggle" => "tooltip", :title => ""}
    %span.glyphicon.glyphicon-eye-close{"aria-hidden" => "true"}
  = link_to(destroy_user_session_path, method: :delete, title: "", "data-original-title": "Logout", "data-placement": "top", "data-toggle": "tooltip" ) do
    %span.glyphicon.glyphicon-off{"aria-hidden" => "true"}

app/views/shared/sidebar/_menu.html.haml
#sidebar-menu.main_menu_side.hidden-print.main_menu
  .menu_section
    %h3 General
    %ul.nav.side-menu
      - if can? :manage, :all
        -# TODOS - For admins only
        %li
          = link_to(profile_index_path) do
            %i.fa.fa-comment
            Company Profile
        %li
          = link_to(profile_index_path) do
            %i.fa.fa-users
            All Employees
        %li
          = link_to(profile_index_path) do
            %i.fa.fa-calendar-o
            Staff Leave Days and Rollover
        %li
          = link_to(profile_index_path) do
            %i.fa.fa-calendar-check-o
            Staff Leave Approval
        %li
          = link_to(profile_index_path) do
            %i.fa.fa-cog
            Public Holidays Settings
        %li
          = link_to(profile_index_path) do
            %i.fa.fa-cog
            Staff Rate Settings
        %li
          = link_to(profile_index_path) do
            %i.fa.fa-cog
            Financial Year Settings
        %li
          = link_to(profile_index_path) do
            %i.fa.fa-question-circle-o
            Accounting Codes
        %li
          = link_to(profile_index_path) do
            %i.fa.fa-lock
            Master Profile
      %li
        = link_to(profile_index_path) do
          %i.fa.fa-address-card
          Profile
      %li
        = link_to(email_index_path) do
          %i.fa.fa-envelope
          Email
      - if can? :manage, Timesheet  
        %li
          -# TODO for supervisors only
          = link_to(timesheet_index_path) do
            %i.fa.fa-calendar-o
            All Staff Timesheet    
      %li
        = link_to(timesheet_index_path) do
          %i.fa.fa-calendar
          My Timesheet
      - if can? :manage, Timesheet  
        %li
          -# TODO for supervisors only
          = link_to(reporting_index_path) do
            %i.fa.fa-bar-chart            
            Staff Productivity Chart
      %li
        = link_to(reporting_index_path) do
          %i.fa.fa-line-chart            
          My Reporting Chart

app/views/shared/sidebar/_profile.html.haml
.profile.clearfix
  .profile_pic
    = image_tag("profile-default.png", :class => "img-circle profile_img", :alt => "...")
  .profile_info
    %span Welcome
    %h2 #{current_user.username}
/ /menu profile quick info
%br/

app/views/shared/sidebar/_top.html.haml
.navbar.nav_title{:style => "border: 0;"}
  %a.site_title{:href => "/"}
    %i.fa.fa-paw
    %span Timesheet Ruby
.clearfix